[package]
name = "shared-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
minifb = "0.25.0"
tokio = { version = "1.28", features = ["full"] }
